---
# Configuration of the Cycloid stack
version: '2'
name: 'Notes Demo App'
canonical: 'stack-notes-aws'
keywords:
  - 'ec2'
  - 'aws'
  - 'instance'
  - 'provider:aws'
status: 'private'
description: |
  This stack will deploy a notes application with Cassandra, a java-based API, an Angular front and an Application Load Balancer on AWS (for demo purposes).
author: 'Olivier de Turckheim'
image: |
  https://raw.githubusercontent.com/olivier2t/stack-notes-aws/main/icon.png
technologies:
  - technology: Cassandra
    version: n/a

config:
  default:
    name: 'Default deployment'
    description: 'This pipeline will deploy a demo application'
    cloud_provider: 'aws'

    # Configuration of the CI pipeline
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'

    # Configuration of ansible for provisionning
    #ansible:
    #  cassandra:
    #    path: 'ansible/environments/front.yml.sample'
    #    destination: '($ project $)/ansible/($ environment $)-front.yml'

    # Configuration of terraform to setup the infrastructure
    #terraform:
    #  cassandra:
    #    path: 'terraform/cassandra.tf.sample'
    #    destination: '($ project $)/terraform/($ environment $)/cassandra.tf'
